#!/bin/bash

#file validity checks
if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]
then
  echo "Usage: cpack <source file> [<dest file>]"
  exit 1
fi  

if [[ -f "$1" ]]; then  
    true
else
    echo "Nonexistant file, exiting"
    exit 1
fi  

#names setup
if [ "$#" -eq 2 ]
then
    packname=$2
else
    packname=$1.cpack.cpp
fi

#source packaging
g++ -E -P -D"COMP_PROG_DEPLOY" $1  |\
    sed 's/#pragma DELETETHISPREFIX//g' > $packname
if [ $? -ne 0 ]
then
    echo "[FAIL] Packaging of source failed!"
    exit 1
else
    echo "Packaging of source done!   ($packname)"
fi
